[package]
name = "tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10.1"
futures-util = "0.3.31"
serde = "1"
serde_json = "1"
subxt = "0.32.1"
subxt-metadata = "0.32.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.16", features = ["net"] }
tokio-tungstenite = "0.24.0"

types = { path = "../../types" }
shared = { path = "../../shared" }
clap = { version = "4.4.18", features = ["derive"] }
