name: Update Registry

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-registry:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: 'registry-ci/package-lock.json'

      - name: Install dependencies
        working-directory: registry-ci
        run: npm install

      - name: Run the registry update script
        working-directory: registry-ci
        run: node generate-registry.js

      - name: Check for changes
        id: git_status
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git_status.outputs.changes_detected == 'true'
        id: commit_and_push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="update-registry-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add registry.json
          git commit -m "Update registry.json"
          git push -u origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git_status.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_SECRET }}
          head-branch: ${{ steps.commit_and_push.outputs.branch_name }}
          base-branch: main
          title: "Automated registry update"
          body: |
            This PR was created automatically by the weekly registry update workflow.

            Changes:
            - Updated `registry.json` with the latest network configurations.

